//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:2.0.50727.4952
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.Fixed fixed2;
    
    private Gtk.EventBox eventbox1;
    
    private Gtk.Label label1;
    
    private Gtk.EventBox eventbox2;
    
    private Gtk.Image image1;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize(this);
        // Widget MainWindow
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("Just a feed ticker");
        this.Icon = Stetic.IconLoader.LoadIcon(this, "stock_news", Gtk.IconSize.Menu, 16);
        this.WindowPosition = ((Gtk.WindowPosition)(4));
        this.Resizable = false;
        this.AllowGrow = false;
        this.Gravity = ((Gdk.Gravity)(4));
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.fixed2 = new Gtk.Fixed();
        this.fixed2.Name = "fixed2";
        this.fixed2.HasWindow = false;
        // Container child fixed2.Gtk.Fixed+FixedChild
        this.eventbox1 = new Gtk.EventBox();
        this.eventbox1.Name = "eventbox1";
        // Container child eventbox1.Gtk.Container+ContainerChild
        this.label1 = new Gtk.Label();
        this.label1.WidthRequest = 500;
        this.label1.Name = "label1";
        this.label1.LabelProp = Mono.Unix.Catalog.GetString("<span size=\"x-large\">Please wait....</span>");
        this.label1.UseMarkup = true;
        this.label1.Ellipsize = ((Pango.EllipsizeMode)(3));
        this.eventbox1.Add(this.label1);
        this.fixed2.Add(this.eventbox1);
        Gtk.Fixed.FixedChild w2 = ((Gtk.Fixed.FixedChild)(this.fixed2[this.eventbox1]));
        w2.X = 5;
        w2.Y = 5;
        // Container child fixed2.Gtk.Fixed+FixedChild
        this.eventbox2 = new Gtk.EventBox();
        this.eventbox2.Name = "eventbox2";
        // Container child eventbox2.Gtk.Container+ContainerChild
        this.image1 = new Gtk.Image();
        this.image1.Name = "image1";
        this.image1.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-properties", Gtk.IconSize.Menu, 16);
        this.eventbox2.Add(this.image1);
        this.fixed2.Add(this.eventbox2);
        Gtk.Fixed.FixedChild w4 = ((Gtk.Fixed.FixedChild)(this.fixed2[this.eventbox2]));
        w4.X = 486;
        w4.Y = 28;
        this.Add(this.fixed2);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 513;
        this.DefaultHeight = 73;
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        this.eventbox1.ButtonPressEvent += new Gtk.ButtonPressEventHandler(this.OnEventbox1ButtonPressEvent);
        this.eventbox2.ButtonPressEvent += new Gtk.ButtonPressEventHandler(this.OnImage1ButtonPressEvent);
        this.image1.ButtonPressEvent += new Gtk.ButtonPressEventHandler(this.OnImage1ButtonPressEvent);
    }
}
